import React, { createContext, useState, useEffect, ReactNode, useContext } from 'react';

// Define translations
const translations: { [key: string]: { [key: string]: string } } = {
  en: {
    // General
    language: 'Language',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    generate: 'Generate',
    generate_image: 'Generate Image',
    upload: 'Upload',
    add: 'Add',
    remove: 'Remove',
    clear: 'Clear',
    send: 'Send',
    search_placeholder: 'Search...',
    no_match_search: 'No items match your search.',
    adjust_filters_search: 'Try adjusting your filters or search query.',
    name: 'Name',
    type: 'Type',
    description: 'Description',
    abilities: 'Abilities',
    traits: 'Traits',
    spells: 'Spells',
    level: 'Level',
    enhance_description: 'Enhance description with AI',
    use: 'Use',
    all: 'All',
    is_empty: 'is empty',
    current: 'Current',
    max: 'Max',
    hp: 'HP',
    armor_class: 'Armor Class',
    attack_bonus: 'Attack Bonus',

    // Header
    header_title: 'RPG System Creator',
    file: 'File',
    view: 'View',
    ai_tools: 'AI Tools',
    help: 'Help',

    // Sidebar
    sidebar_title: 'Creation Kit',
    dashboard: 'Dashboard',
    setting: 'Setting',
    weapons: 'Weapons',
    items: 'Items',
    gear: 'Clothes & Gear',
    npcs: 'NPCs',
    creatures: 'Creatures',
    classes: 'Classes',
    races: 'Races',
    characters: 'Character Sheets',
    analytics: 'Analytics',
    campaign_generator: 'AI Campaign Gen',
    image_generator: 'AI Image Gen',

    // Dashboard
    dashboard_welcome: 'Welcome to your RPG System for',
    dashboard_summary: "Here's a summary of your world.",
    dashboard_welcome_no_name: "Welcome to your RPG System. Give your world a name on the Setting page to get started!",
    weapons_created: 'Weapons Created',
    spells_created: 'Spells Created',
    npcs_defined: 'NPCs Defined',
    classes_available: 'Classes Available',
    races_playable: 'Races Playable',
    world_lore: 'World Lore',
    
    // Setting
    world_setting: 'World Setting',
    world_name: 'World Name',
    world_history: 'History',
    save_setting: 'Save Setting',
    settings_saved: 'Settings saved!',
    world_name_placeholder: 'Enter the name of your world',
    world_lore_placeholder: 'Describe the core themes, magic systems, and general atmosphere of your world.',
    world_history_placeholder: 'Outline the major historical events, ancient civilizations, and recent conflicts.',


    // Forms & Creation
    generate_with_ai: 'Generate with AI',
    add_weapon: 'Add Weapon',
    
    edit_weapon: 'Edit Weapon',
    add_new_weapon: 'Add New Weapon',
    damage: 'Damage',
    weapon_image: 'Weapon Image',
    save_weapon: 'Save Weapon',
    confirm_delete_weapon: 'Are you sure you want to delete the weapon "{name}"?',
    weapon_ai_placeholder: 'A sword forged from a fallen star',
    weapon_type_placeholder: 'Sword, Axe, Bow',
    weapon_damage_placeholder: '1d8 slashing',
    no_weapons_created: 'No weapons created yet.',
    start_creating_weapons: 'Click "Add Weapon" to start building your arsenal.',
    search_placeholder_weapons: 'Search weapons...',
    all_types: 'All Types',
    generate_description_with_ai: 'Generate Description with AI',
    weapon_description_ai_placeholder: 'e.g., glows when orcs are near',

    // Items
    add_item: 'Add Item',
    edit_item: 'Edit Item',
    add_new_item: 'Add New Item',
    effects: 'Effects',
    item_icon: 'Item Icon',
    save_item: 'Save Item',
    item_ai_placeholder: 'A compass that points to what you desire',
    item_type_placeholder: 'Potion, Scroll, Ring',
    effect_description_placeholder: 'Describe the mechanical effect',
    add_effect: '+ Add Effect',
    'search_placeholder_items': 'Search items...',
    'no_items_created': 'No items created yet.',
    'start_creating_items': 'Click "Add Item" to create treasures for your world.',
    'confirm_delete_item': 'Are you sure you want to delete the item "{name}"?',

    // Gear
    'add_gear': 'Add Gear',
    'edit_gear': 'Edit Gear',
    'add_new_gear': 'Add New Gear',
    slot: 'Slot',
    armor_value: 'Armor Value',
    gear_image: 'Gear Image',
    'save_gear': 'Save Gear',
    'gear_ai_placeholder': 'Enchanted leather armor of the forest',
    'gear_type_placeholder': 'Light Armor, Clothing',
    'gear_slot_placeholder': 'Head, Chest, Feet',
    'gear_armor_value_placeholder': '14 + Dex, 5, or None',
    'search_placeholder_gear': 'Search gear...',
    'all_slots': 'All Slots',
    no_gear_created: 'No clothes or gear created yet.',
    'start_creating_gear': 'Click "Add Gear" to create armor and outfits for your world.',
    'confirm_delete_gear': 'Are you sure you want to delete the gear "{name}"?',
    'no_gear_match_search': 'No gear matches your search.',
    
    // Spells
    'add_spell': 'Add Spell',
    'edit_spell': 'Edit Spell',
    'add_new_spell': 'Add New Spell',
    'school': 'School',
    'effect': 'Effect',
    'mana_cost': 'Mana Cost',
    'range': 'Range',
    'spell_icon': 'Spell Icon',
    'generate_spell_icon': 'Generate Spell Icon',
    'save_spell': 'Save Spell',
    spell_school: 'Spell School',
    spell_level: 'Spell Level',
    cantrip: 'Cantrip',
    spell_effect_prompt: 'Spell Effect Prompt',
    'spell_ai_placeholder': 'A fireball that bounces between enemies',
    'spell_school_placeholder': 'Evocation, Illusion',
    'spell_effect_placeholder': 'Describe what the spell does...',
    'search_placeholder_spells': 'Search spells...',
    'all_schools': 'All Schools',
    'all_levels': 'All Levels',
    'no_spells_created': 'No spells created yet.',
    'start_creating_spells': 'Click "Add Spell" to create the magic of your world.',
    'confirm_delete_spell': 'Are you sure you want to delete the spell "{name}"?',
    generate_effect_with_ai: 'Generate Effect with AI',
    spell_effect_ai_placeholder: 'e.g., creates an illusion of a dragon',

    // Classes
    'add_class': 'Add Class',
    'edit_class': 'Edit Class',
    'add_new_class': 'Add New Class',
    'class_name': 'Class Name',
    no_spells_for_class: 'No spells created yet. Go to the Spells screen to add some.',
    'search_placeholder_spells_class': 'Search spells...',
    'save_class': 'Save Class',
    'no_classes_created': 'No classes created yet.',
    'start_creating_classes': 'Click "Add Class" to define the archetypes of your world.',
    'confirm_delete_class': 'Are you sure you want to delete the class "{name}"?',
    'class_ai_placeholder': 'A warrior who commands shadows',
    'ability_placeholder': 'Ability #{index}',
    'add_ability': '+ Add Ability',
    'trait_placeholder': 'Trait #{index}',
    'add_trait': '+ Add Trait',

    // Races
    'add_race': 'Add Race',
    'edit_race': 'Edit Race',
    'add_new_race': 'Add New Race',
    'race_name': 'Race Name',
    'traits_and_abilities': 'Traits & Abilities',
    'save_race': 'Save Race',
    'no_races_created': 'No races created yet.',
    'start_creating_races': 'Click "Add Race" to define the peoples of your world.',
    'confirm_delete_race': 'Are you sure you want to delete the race "{name}"?',
    'race_ai_placeholder': 'A race of crystalline humanoids',

    // Characters
    'create_character': 'Create Character',
    'edit_character': 'Edit Character',
    'create_new_character': 'Create New Character',
    'physical_appearance': 'Physical Appearance',
    'background_history': 'Background / History',
    'attributes': 'Attributes',
    'health_points': 'Health Points',
    'mana_points': 'Mana Points',
    'spell_slots': 'Spell Slots',
    'level_n_slots': 'Level {level} Slots',
    'no_spell_slots': "This character's class has no spells.",
    'new_attribute_name': 'New attribute name',
    'save_changes': 'Save Changes',
    'no_characters_created': 'No characters created yet.',
    'start_creating_characters': 'Click "Create Character" to start bringing your heroes to life.',
    'confirm_delete_character': 'Are you sure you want to delete the character "{name}"?',
    inventory: 'Inventory',
    inventory_management: 'Inventory Management',
    no_items_for_character: 'No items created in the system.',
    no_gear_for_character: 'No gear created in the system.',
    no_weapons_for_character: 'No weapons created in the system.',
    'search_placeholder_items_character': 'Search items to add...',
    'search_placeholder_gear_character': 'Search gear to add...',
    'search_placeholder_weapons_character': 'Search weapons to add...',
    'character_portrait': 'Character Portrait',
    'ai_generation_reference': 'AI Generation Reference',
    'upload_photo_for_ai': 'Upload a photo for the AI to use as inspiration.',
    'upload_reference_photo': 'Upload Reference Photo',
    'generate_from_photo': 'Generate from Photo',
    'change_photo': 'Change Photo',
    'remove_photo': 'Remove Photo',
    'upload_portrait': 'Upload Portrait',
    'character_inventory': "Character's Inventory",
    quantity: 'Qty',
    increase_quantity: 'Increase quantity',
    decrease_quantity: 'Decrease quantity',
    equip: 'Equip',
    unequip: 'Unequip',
    equip_main: 'Equip Main',
    equip_off: 'Equip Off',
    backpack: 'Backpack',
    'search_in_backpack': 'Search in backpack...',
    equipped_gear: 'Equipped Gear',
    equipped_weapons: 'Equipped Weapons',
    head: 'Head',
    chest: 'Chest',
    legs: 'Legs',
    hands: 'Hands',
    feet: 'Feet',
    accessory: 'Accessory',
    main_hand: 'Main Hand',
    off_hand: 'Off Hand',
    add_to_backpack: 'Add to Backpack',
    calculated_combat_stats: 'Calculated Combat Stats',
    damage_output: 'Damage Output',
    drop_to_equip: 'Drop to Equip',
    drop_to_unequip: 'Drop in Backpack',


    // Campaign Gen
    'ai_dungeon_master': 'AI Dungeon Master',
    campaign_started_prompt: 'Interact with the world. Describe your actions, speak to characters, and see how the story unfolds.',
    campaign_not_started_prompt: 'Describe a theme or starting point, and the AI will begin a dynamic campaign for you.',
    'theme_selection_title': 'Choose a Campaign Theme',
    'theme_high_fantasy': 'High Fantasy',
    'theme_high_fantasy_desc': 'Epic quests, clear heroes and villains, and world-saving stakes.',
    'theme_grimdark': 'Grimdark',
    'theme_grimdark_desc': 'A dark, morally grey world where every victory comes at a cost.',
    'theme_mystery': 'Mystery',
    'theme_mystery_desc': 'Unravel a complex crime or conspiracy using wits and investigation.',
    'theme_intrigue': 'Political Intrigue',
    'theme_intrigue_desc': 'Navigate a web of secrets, alliances, and betrayals in the halls of power.',
    'theme_exploration': 'Exploration',
    'theme_exploration_desc': 'Journey into the unknown, discover lost lands, and map the wilderness.',
    'theme_custom': 'Custom',
    'theme_custom_desc': 'Write your own unique campaign prompt from scratch.',
    'campaign_details_placeholder': 'Add any specific details or twists...',
    'campaign_custom_placeholder': 'Describe your campaign idea...',
    start_campaign: 'Start Campaign',
    chat_input_placeholder: 'What do you do?',
    error_starting_campaign: 'Failed to start the campaign. Please check the console for details.',
    error_sending_message: 'Failed to get a response from the AI. Please try again.',

    // Image Gen
    ai_image_generator: 'AI Image Generator',
    image_generator_subtitle: 'Bring your world to life. Generate artwork for your creations.',
    generation_type: 'Generation Type',
    landscape: 'Landscape',
    world_map: 'World Map',
    other: 'Other',
    prompt: 'Prompt',
    additional_details: 'Additional Details',
    image_gen_placeholder_other: 'A fierce dragon guarding its treasure',
    image_gen_placeholder_details: 'Cinematic lighting, during a storm',
    image_gen_output_placeholder: 'Your generated image will appear here.',
    final_prompt: 'Final Prompt',
    error_generating_image: 'Failed to generate image. Please check the console for details.',
    error_unexpected: 'An unexpected error occurred.',

    // NPCs
    edit_npc: 'Edit NPC',
    add_new_npc: 'Add New NPC',
    npc_ai_placeholder: 'A reclusive elven loremaster',
    race: 'Race',
    role: 'Role',
    npc_race_placeholder: 'Human, Elf, Orc',
    npc_role_placeholder: 'Quest Giver, Merchant',
    portrait_style: 'Portrait Style',
    save_npc: 'Save NPC',
    confirm_delete_npc: 'Are you sure you want to delete the NPC "{name}"?',
    search_placeholder_npcs: 'Search NPCs...',
    all_races: 'All Races',
    all_roles: 'All Roles',
    no_npcs_created: 'No NPCs created yet.',
    start_creating_npcs: 'Click "Add NPC" to populate your world with characters.',
    
    // Creatures
    edit_creature: 'Edit Creature',
    add_new_creature: 'Add New Creature',
    creature_ai_placeholder: 'A giant spider that spins webs of glass',
    challenge_rating: 'Challenge Rating',
    creature_type_placeholder: 'Beast, Monstrosity, Undead',
    creature_cr_placeholder: '1/2, 5 (1,800 XP)',
    creature_hp_placeholder: 'e.g., 45 (6d10 + 12)',
    creature_ac_placeholder: 'e.g., 15 (Natural Armor)',
    creature_ab_placeholder: 'e.g., +5',
    save_creature: 'Save Creature',
    confirm_delete_creature: 'Are you sure you want to delete the creature "{name}"?',
    search_placeholder_creatures: 'Search creatures...',
    no_creatures_created: 'No creatures created yet.',
    start_creating_creatures: 'Click "Add New Creature" to design the monsters for your world.',
    ability: 'Ability',
    add_ability_creature: '+ Add Ability',
    ability_placeholder_creature: 'Ability #{index}',

    // Effect Types
    'effect_type_healing': 'Healing',
    'effect_type_damage': 'Damage',
    'effect_type_buff': 'Buff',
    'effect_type_debuff': 'Debuff',
    'effect_type_utility': 'Utility',
    'effect_type_other': 'Other',

    // Spell Schools
    'spell_school_evocation': 'Evocation',
    'spell_school_illusion': 'Illusion',
    'spell_school_necromancy': 'Necromancy',
    'spell_school_conjuration': 'Conjuration',
    'spell_school_abjuration': 'Abjuration',
    'spell_school_divination': 'Divination',
    'spell_school_enchantment': 'Enchantment',
    'spell_school_transmutation': 'Transmutation',
    'spell_school_artificing': 'Artificing',
    'spell_school_psionics': 'Psionics',
    
    // Attributes
    'Strength': 'Strength',
    'Dexterity': 'Dexterity',
    'Constitution': 'Constitution',

    // Project Management
    'new_project': 'New',
    'load_project': 'Load',
    'save_project': 'Save',
    'confirm_new_project': 'Are you sure you want to start a new project? This will clear all current data.',
    'project_loaded_successfully': 'Project loaded successfully!',
    'error_loading_project': 'Failed to load project file. The file might be corrupted or in the wrong format.',

    // Deletion
    'delete_weapon': '- Delete Weapon',
    'delete_item': '- Delete Item',
    'delete_gear': '- Delete Gear',
    'delete_spell': '- Delete Spell',
    'delete_npc': '- Delete NPC',
    'delete_creature': '- Delete Creature',
    'delete_class': '- Delete Class',
    'delete_race': '- Delete Race',
    'delete_character': '- Delete Character',
    'cancel_deletion': 'Cancel Deletion',
    'confirm_deletion': 'Confirm Deletion',
    warning_delete_dependency: "Warning: The following characters use this {entity}: {character_list}. Deleting it will also remove it from their sheets. Are you sure you want to delete {name}?",
    block_delete_dependency: "Cannot delete {name}. The following characters are assigned this {entity}: {character_list}. Please update these characters first.",
    entity_weapon: "weapon",
    entity_item: "item",
    entity_gear: "piece of gear",
    entity_spell: "spell",
    entity_class: "class",
    entity_race: "race",

    // Analytics Screen
    analytics_title: 'World Analytics',
    analytics_subtitle: 'Visualize the composition of your RPG world with these charts and statistics.',
    items_by_type: 'Items by Type',
    spells_by_school: 'Spells by School',
    creatures_by_cr: 'Creatures by Challenge Rating',
    npcs_by_role: 'NPCs by Role',
    weapons_by_type: 'Weapons by Type',
    no_data_for_chart: 'No data available to display.',
    challenge_rating_group: 'CR {range}',
  },
  es: {
    // General
    language: 'Idioma',
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar',
    generate: 'Generar',
    generate_image: 'Generar Imagen',
    upload: 'Subir',
    add: 'Añadir',
    remove: 'Quitar',
    clear: 'Limpiar',
    send: 'Enviar',
    search_placeholder: 'Buscar...',
    no_match_search: 'No hay resultados para tu búsqueda.',
    adjust_filters_search: 'Intenta ajustar tus filtros o tu búsqueda.',
    name: 'Nombre',
    type: 'Tipo',
    description: 'Descripción',
    abilities: 'Habilidades',
    traits: 'Rasgos',
    spells: 'Hechizos',
    level: 'Nivel',
    enhance_description: 'Mejorar descripción con IA',
    use: 'Usar',
    all: 'Todo',
    is_empty: 'está vacía',
    current: 'Actual',
    max: 'Máx',
    hp: 'PV',
    armor_class: 'Clase de Armadura',
    attack_bonus: 'Bono de Ataque',
    
    // Header
    header_title: 'Creador de Sistemas RPG',
    file: 'Archivo',
    view: 'Ver',
    ai_tools: 'Herramientas IA',
    help: 'Ayuda',

    // Sidebar
    sidebar_title: 'Kit de Creación',
    dashboard: 'Panel',
    setting: 'Mundo',
    weapons: 'Armas',
    items: 'Objetos',
    gear: 'Ropa y Equipo',
    npcs: 'PNJs',
    creatures: 'Criaturas',
    classes: 'Clases',
    races: 'Razas',
    characters: 'Hojas de Personaje',
    analytics: 'Análisis',
    campaign_generator: 'Gen de Campañas IA',
    image_generator: 'Gen de Imágenes IA',

    // Dashboard
    dashboard_welcome: 'Bienvenido a tu sistema de RPG para',
    dashboard_summary: 'Aquí tienes un resumen de tu mundo.',
    dashboard_welcome_no_name: "Bienvenido a tu sistema de RPG. ¡Dale un nombre a tu mundo en la página de Ambientación para empezar!",
    weapons_created: 'Armas Creadas',
    spells_created: 'Hechizos Creados',
    npcs_defined: 'PNJs Definidos',
    classes_available: 'Clases Disponibles',
    races_playable: 'Razas Jugables',
    world_lore: 'Lore del Mundo',

    // Setting
    world_setting: 'Ambientación del Mundo',
    world_name: 'Nombre del Mundo',
    world_history: 'Historia',
    save_setting: 'Guardar Ambientación',
    settings_saved: '¡Ajustes guardados!',
    world_name_placeholder: 'Introduce el nombre de tu mundo',
    world_lore_placeholder: 'Describe los temas centrales, sistemas de magia y la atmósfera general de tu mundo.',
    world_history_placeholder: 'Resume los eventos históricos más importantes, civilizaciones antiguas y conflictos recientes.',
    
    // Forms & Creation
    generate_with_ai: 'Generar con IA',
    add_weapon: 'Añadir Arma',
    edit_weapon: 'Editar Arma',
    add_new_weapon: 'Añadir Nueva Arma',
    damage: 'Daño',
    weapon_image: 'Imagen del Arma',
    save_weapon: 'Guardar Arma',
    confirm_delete_weapon: '¿Estás seguro de que quieres eliminar el arma "{name}"?',
    weapon_ai_placeholder: 'Una espada forjada de una estrella caída',
    weapon_type_placeholder: 'Espada, Hacha, Arco',
    weapon_damage_placeholder: '1d8 cortante',
    no_weapons_created: 'No se han creado armas todavía.',
    start_creating_weapons: 'Haz clic en "Añadir Arma" para empezar a construir tu arsenal.',
    search_placeholder_weapons: 'Buscar armas...',
    all_types: 'Todos los tipos',
    generate_description_with_ai: 'Generar Descripción con IA',
    weapon_description_ai_placeholder: 'ej: brilla cuando hay orcos cerca',

    // Items
    add_item: 'Añadir Objeto',
    edit_item: 'Editar Objeto',
    add_new_item: 'Añadir Nuevo Objeto',
    effects: 'Efectos',
    item_icon: 'Icono del Objeto',
    save_item: 'Guardar Objeto',
    item_ai_placeholder: 'Una brújula que apunta a lo que deseas',
    item_type_placeholder: 'Poción, Pergamino, Anillo',
    effect_description_placeholder: 'Describe el efecto mecánico',
    add_effect: '+ Añadir Efecto',
    'search_placeholder_items': 'Buscar objetos...',
    'no_items_created': 'No se han creado objetos todavía.',
    'start_creating_items': 'Haz clic en "Añadir Objeto" para crear tesoros para tu mundo.',
    'confirm_delete_item': '¿Estás seguro de que quieres eliminar el objeto "{name}"?',

    // Gear
    'add_gear': 'Añadir Equipo',
    'edit_gear': 'Editar Equipo',
    'add_new_gear': 'Añadir Nuevo Equipo',
    slot: 'Espacio',
    'armor_value': 'Valor de Armadura',
    'gear_image': 'Imagen del Equipo',
    'save_gear': 'Guardar Equipo',
    'gear_ai_placeholder': 'Armadura de cuero encantada del bosque',
    'gear_type_placeholder': 'Armadura Ligera, Ropa',
    'gear_slot_placeholder': 'Cabeza, Pecho, Pies',
    'gear_armor_value_placeholder': '14 + Des, 5, o Ninguno',
    'search_placeholder_gear': 'Buscar equipo...',
    'all_slots': 'Todos los espacios',
    'no_gear_created': 'No se ha creado ropa o equipo todavía.',
    'start_creating_gear': 'Haz clic en "Añadir Equipo" para crear armaduras y atuendos para tu mundo.',
    'confirm_delete_gear': '¿Estás seguro de que quieres eliminar la pieza de equipo "{name}"?',
    'no_gear_match_search': 'Ningún equipo coincide con tu búsqueda.',
    
    // Spells
    'add_spell': 'Añadir Hechizo',
    'edit_spell': 'Editar Hechizo',
    'add_new_spell': 'Añadir Nuevo Hechizo',
    'school': 'Escuela',
    'effect': 'Efecto',
    'mana_cost': 'Coste de Maná',
    'range': 'Alcance',
    'spell_icon': 'Icono del Hechizo',
    'generate_spell_icon': 'Generar Icono de Hechizo',
    'save_spell': 'Guardar Hechizo',
    'spell_school': 'Escuela de Magia',
    'spell_level': 'Nivel del Hechizo',
    'cantrip': 'Truco',
    'spell_effect_prompt': 'Prompt del Efecto del Hechizo',
    'spell_ai_placeholder': 'Una bola de fuego que rebota entre enemigos',
    'spell_school_placeholder': 'Evocación, Ilusión',
    'spell_effect_placeholder': 'Describe lo que hace el hechizo...',
    'search_placeholder_spells': 'Buscar hechizos...',
    'all_schools': 'Todas las escuelas',
    'all_levels': 'Todos los niveles',
    'no_spells_created': 'No se han creado hechizos todavía.',
    'start_creating_spells': 'Haz clic en "Añadir Hechizo" para crear la magia de tu mundo.',
    'confirm_delete_spell': '¿Estás seguro de que quieres eliminar el hechizo "{name}"?',
    generate_effect_with_ai: 'Generar Efecto con IA',
    spell_effect_ai_placeholder: 'ej: crea una ilusión de un dragón',

    // Classes
    'add_class': 'Añadir Clase',
    'edit_class': 'Editar Clase',
    'add_new_class': 'Añadir Nueva Clase',
    'class_name': 'Nombre de la Clase',
    'no_spells_for_class': 'No se han creado hechizos todavía. Ve a la pantalla de Hechizos para añadir algunos.',
    'search_placeholder_spells_class': 'Buscar hechizos...',
    'save_class': 'Guardar Clase',
    'no_classes_created': 'No se han creado clases todavía.',
    'start_creating_classes': 'Haz clic en "Añadir Clase" para definir los arquetipos de tu mundo.',
    'confirm_delete_class': '¿Estás seguro de que quieres eliminar la clase "{name}"?',
    'class_ai_placeholder': 'Un guerrero que comanda las sombras',
    'ability_placeholder': 'Habilidad #{index}',
    'add_ability': '+ Añadir Habilidad',
    'trait_placeholder': 'Rasgo #{index}',
    'add_trait': '+ Añadir Rasgo',

    // Races
    'add_race': 'Añadir Raza',
    'edit_race': 'Editar Raza',
    'add_new_race': 'Añadir Nueva Raza',
    'race_name': 'Nombre de la Raza',
    'traits_and_abilities': 'Rasgos y Habilidades',
    'save_race': 'Guardar Raza',
    'no_races_created': 'No se han creado razas todavía.',
    'start_creating_races': 'Haz clic en "Añadir Raza" para definir los pueblos de tu mundo.',
    'confirm_delete_race': '¿Estás seguro de que quieres eliminar la raza "{name}"?',
    'race_ai_placeholder': 'Una raza de humanoides cristalinos',

    // Characters
    'create_character': 'Crear Personaje',
    'edit_character': 'Editar Personaje',
    'create_new_character': 'Crear Nuevo Personaje',
    'physical_appearance': 'Apariencia Física',
    'background_history': 'Trasfondo / Historia',
    'attributes': 'Atributos',
    'health_points': 'Puntos de Vida',
    'mana_points': 'Puntos de Maná',
    'spell_slots': 'Espacios de Hechizo',
    'level_n_slots': 'Espacios Nivel {level}',
    'no_spell_slots': 'La clase de este personaje no tiene hechizos.',
    'new_attribute_name': 'Nuevo nombre de atributo',
    'save_changes': 'Guardar Cambios',
    'no_characters_created': 'No se han creado personajes todavía.',
    'start_creating_characters': 'Haz clic en "Crear Personaje" para dar vida a tus héroes.',
    'confirm_delete_character': '¿Estás seguro de que quieres eliminar al personaje "{name}"?',
    inventory: 'Inventario',
    inventory_management: 'Gestión de Inventario',
    no_items_for_character: 'No hay objetos creados en el sistema.',
    no_gear_for_character: 'No hay equipo creado en el sistema.',
    no_weapons_for_character: 'No hay armas creadas en el sistema.',
    'search_placeholder_items_character': 'Buscar objetos para añadir...',
    'search_placeholder_gear_character': 'Buscar equipo para añadir...',
    'search_placeholder_weapons_character': 'Buscar armas para añadir...',
    'character_portrait': 'Retrato del Personaje',
    'ai_generation_reference': 'Referencia para Generación IA',
    'upload_photo_for_ai': 'Sube una foto para que la IA la use como inspiración.',
    'upload_reference_photo': 'Subir Foto de Referencia',
    'generate_from_photo': 'Generar desde Foto',
    'change_photo': 'Cambiar Foto',
    'remove_photo': 'Quitar Foto',
    'upload_portrait': 'Subir Retrato',
    'character_inventory': 'Inventario del Personaje',
    quantity: 'Cant',
    increase_quantity: 'Aumentar cantidad',
    decrease_quantity: 'Disminuir cantidad',
    equip: 'Equipar',
    unequip: 'Desequipar',
    equip_main: 'Equipar Principal',
    equip_off: 'Equipar Secundaria',
    backpack: 'Mochila',
    'search_in_backpack': 'Buscar en la mochila...',
    equipped_gear: 'Equipo Equipado',
    equipped_weapons: 'Armas Equipadas',
    head: 'Cabeza',
    chest: 'Pecho',
    legs: 'Piernas',
    hands: 'Manos',
    feet: 'Pies',
    accessory: 'Accesorio',
    main_hand: 'Mano Principal',
    off_hand: 'Mano Secundaria',
    add_to_backpack: 'Añadir a la Mochila',
    calculated_combat_stats: 'Estadísticas de Combate',
    damage_output: 'Daño Causado',
    drop_to_equip: 'Arrastra para Equipar',
    drop_to_unequip: 'Arrastra a la Mochila',


    // Campaign Gen
    'ai_dungeon_master': 'Director de Juego IA',
    campaign_started_prompt: 'Interactúa con el mundo. Describe tus acciones, habla con personajes y mira cómo se desarrolla la historia.',
    campaign_not_started_prompt: 'Describe un tema o punto de partida, y la IA iniciará una campaña dinámica para ti.',
    'theme_selection_title': 'Elige un Tema de Campaña',
    'theme_high_fantasy': 'Alta Fantasía',
    'theme_high_fantasy_desc': 'Misiones épicas, héroes y villanos claros, y el destino del mundo en juego.',
    'theme_grimdark': 'Grimdark',
    'theme_grimdark_desc': 'Un mundo oscuro y moralmente gris donde cada victoria tiene un coste.',
    'theme_mystery': 'Misterio',
    'theme_mystery_desc': 'Resuelve un crimen complejo o una conspiración usando tu ingenio e investigación.',
    'theme_intrigue': 'Intriga Política',
    'theme_intrigue_desc': 'Navega por una red de secretos, alianzas y traiciones en los salones del poder.',
    'theme_exploration': 'Exploración',
    'theme_exploration_desc': 'Viaja a lo desconocido, descubre tierras perdidas y mapea la naturaleza.',
    'theme_custom': 'Personalizado',
    'theme_custom_desc': 'Escribe tu propia idea de campaña única desde cero.',
    'campaign_details_placeholder': 'Añade detalles específicos o giros...',
    'campaign_custom_placeholder': 'Describe tu idea de campaña...',
    start_campaign: 'Iniciar Campaña',
    chat_input_placeholder: '¿Qué haces?',
    error_starting_campaign: 'Error al iniciar la campaña. Por favor, revisa la consola para más detalles.',
    error_sending_message: 'Error al obtener respuesta de la IA. Por favor, inténtalo de nuevo.',
    
    // Image Gen
    ai_image_generator: 'Generador de Imágenes IA',
    image_generator_subtitle: 'Da vida a tu mundo. Genera arte para tus creaciones.',
    generation_type: 'Tipo de Generación',
    landscape: 'Paisaje',
    world_map: 'Mapa del Mundo',
    other: 'Otro',
    prompt: 'Prompt',
    additional_details: 'Detalles Adicionales',
    image_gen_placeholder_other: 'Un dragón feroz guardando su tesoro',
    image_gen_placeholder_details: 'Iluminación cinemática, durante una tormenta',
    image_gen_output_placeholder: 'Tu imagen generada aparecerá aquí.',
    final_prompt: 'Prompt Final',
    error_generating_image: 'Error al generar la imagen. Por favor, revisa la consola para más detalles.',
    error_unexpected: 'Ocurrió un error inesperado.',
    
    // NPCs
    edit_npc: 'Editar PNJ',
    add_new_npc: 'Añadir Nuevo PNJ',
    npc_ai_placeholder: 'Un erudito elfo solitario',
    race: 'Raza',
    role: 'Rol',
    npc_race_placeholder: 'Humano, Elfo, Orco',
    npc_role_placeholder: 'Da misiones, Mercader',
    portrait_style: 'Estilo del Retrato',
    save_npc: 'Guardar PNJ',
    confirm_delete_npc: '¿Estás seguro de que quieres eliminar al PNJ "{name}"?',
    search_placeholder_npcs: 'Buscar PNJs...',
    all_races: 'Todas las razas',
    all_roles: 'Todos los roles',
    no_npcs_created: 'No se han creado PNJs todavía.',
    start_creating_npcs: 'Haz clic en "Añadir PNJ" para poblar tu mundo con personajes.',

    // Creatures
    edit_creature: 'Editar Criatura',
    add_new_creature: 'Añadir Nueva Criatura',
    creature_ai_placeholder: 'Una araña gigante que teje telarañas de cristal',
    challenge_rating: 'Valor de Desafío',
    creature_type_placeholder: 'Bestia, Monstruosidad, No-muerto',
    creature_cr_placeholder: '1/2, 5 (1,800 XP)',
    creature_hp_placeholder: 'ej: 45 (6d10 + 12)',
    creature_ac_placeholder: 'ej: 15 (Armadura Natural)',
    creature_ab_placeholder: 'ej: +5',
    save_creature: 'Guardar Criatura',
    confirm_delete_creature: '¿Estás seguro de que quieres eliminar la criatura "{name}"?',
    search_placeholder_creatures: 'Buscar criaturas...',
    no_creatures_created: 'No se han creado criaturas todavía.',
    start_creating_creatures: 'Haz clic en "Añadir Nueva Criatura" para diseñar los monstruos de tu mundo.',
    ability: 'Habilidad',
    add_ability_creature: '+ Añadir Habilidad',
    ability_placeholder_creature: 'Habilidad #{index}',
    
    // Effect Types
    'effect_type_healing': 'Curación',
    'effect_type_damage': 'Daño',
    'effect_type_buff': 'Mejora',
    'effect_type_debuff': 'Empeoramiento',
    'effect_type_utility': 'Utilidad',
    'effect_type_other': 'Otro',

    // Spell Schools
    'spell_school_evocation': 'Evocación',
    'spell_school_illusion': 'Ilusión',
    'spell_school_necromancy': 'Nigromancia',
    'spell_school_conjuration': 'Conjuración',
    'spell_school_abjuration': 'Abjuración',
    'spell_school_divination': 'Adivinación',
    'spell_school_enchantment': 'Encantamiento',
    'spell_school_transmutation': 'Transmutación',
    'spell_school_artificing': 'Artificería',
    'spell_school_psionics': 'Psiónica',

    // Attributes
    'Strength': 'Fuerza',
    'Dexterity': 'Destreza',
    'Constitution': 'Constitución',

    // Project Management
    'new_project': 'Nuevo',
    'load_project': 'Cargar',
    'save_project': 'Guardar',
    'confirm_new_project': '¿Estás seguro de que quieres empezar un nuevo proyecto? Esto borrará todos los datos actuales.',
    'project_loaded_successfully': '¡Proyecto cargado con éxito!',
    'error_loading_project': 'Error al cargar el archivo del proyecto. El archivo puede estar dañado o en el formato incorrecto.',
    
    // Deletion
    'delete_weapon': '- Eliminar Arma',
    'delete_item': '- Eliminar Objeto',
    'delete_gear': '- Eliminar Equipo',
    'delete_spell': '- Eliminar Hechizo',
    'delete_npc': '- Eliminar PNJ',
    'delete_creature': '- Eliminar Criatura',
    'delete_class': '- Eliminar Clase',
    'delete_race': '- Eliminar Raza',
    'delete_character': '- Eliminar Personaje',
    'cancel_deletion': 'Cancelar Eliminación',
    'confirm_deletion': 'Confirmar Eliminación',
    warning_delete_dependency: "Aviso: Los siguientes personajes usan este {entity}: {character_list}. Eliminarlo también lo quitará de sus fichas. ¿Estás seguro de que quieres eliminar a {name}?",
    block_delete_dependency: "No se puede eliminar {name}. Los siguientes personajes tienen asignado este {entity}: {character_list}. Por favor, actualiza esos personajes primero.",
    entity_weapon: "arma",
    entity_item: "objeto",
    entity_gear: "pieza de equipo",
    entity_spell: "hechizo",
    entity_class: "clase",
    entity_race: "raza",

    // Analytics Screen
    analytics_title: 'Análisis del Mundo',
    analytics_subtitle: 'Visualiza la composición de tu mundo de rol con estos gráficos y estadísticas.',
    items_by_type: 'Objetos por Tipo',
    spells_by_school: 'Hechizos por Escuela',
    creatures_by_cr: 'Criaturas por Valor de Desafío',
    npcs_by_role: 'PNJs por Rol',
    weapons_by_type: 'Armas por Tipo',
    no_data_for_chart: 'No hay datos disponibles para mostrar.',
    challenge_rating_group: 'VD {range}',
  },
  'pt-BR': {
    // General
    language: 'Idioma',
    edit: 'Editar',
    delete: 'Excluir',
    save: 'Salvar',
    cancel: 'Cancelar',
    generate: 'Gerar',
    generate_image: 'Gerar Imagem',
    upload: 'Carregar',
    add: 'Adicionar',
    remove: 'Remover',
    clear: 'Limpar',
    send: 'Enviar',
    search_placeholder: 'Buscar...',
    no_match_search: 'Nenhum item corresponde à sua busca.',
    adjust_filters_search: 'Tente ajustar seus filtros ou termo de busca.',
    name: 'Nome',
    type: 'Tipo',
    description: 'Descrição',
    abilities: 'Habilidades',
    traits: 'Traços',
    spells: 'Feitiços',
    level: 'Nível',
    enhance_description: 'Aprimorar descrição com IA',
    use: 'Usar',
    all: 'Todos',
    is_empty: 'está vazia',
    current: 'Atual',
    max: 'Máx',
    hp: 'PV',
    armor_class: 'Classe de Armadura',
    attack_bonus: 'Bônus de Ataque',

    // Header
    header_title: 'Criador de Sistemas de RPG',
    file: 'Arquivo',
    view: 'Visualizar',
    ai_tools: 'Ferramentas de IA',
    help: 'Ajuda',

    // Sidebar
    sidebar_title: 'Kit de Criação',
    dashboard: 'Painel',
    setting: 'Cenário',
    weapons: 'Armas',
    items: 'Itens',
    gear: 'Roupas e Equipamentos',
    npcs: 'NPCs',
    creatures: 'Criaturas',
    classes: 'Classes',
    races: 'Raças',
    characters: 'Fichas de Personagem',
    analytics: 'Análises',
    campaign_generator: 'Gerador de Campanha IA',
    image_generator: 'Gerador de Imagem IA',

    // Dashboard
    dashboard_welcome: 'Bem-vindo ao seu sistema de RPG para',
    dashboard_summary: 'Aqui está um resumo do seu mundo.',
    dashboard_welcome_no_name: "Bem-vindo ao seu sistema de RPG. Dê um nome ao seu mundo na página de Cenário para começar!",
    weapons_created: 'Armas Criadas',
    spells_created: 'Feitiços Criados',
    npcs_defined: 'NPCs Definidos',
    classes_available: 'Classes Disponíveis',
    races_playable: 'Raças Jogáveis',
    world_lore: 'Lore do Mundo',
    
    // Setting
    world_setting: 'Cenário do Mundo',
    world_name: 'Nome do Mundo',
    world_history: 'História',
    save_setting: 'Salvar Cenário',
    settings_saved: 'Configurações salvas!',
    world_name_placeholder: 'Digite o nome do seu mundo',
    world_lore_placeholder: 'Descreva os temas centrais, sistemas de magia e a atmosfera geral do seu mundo.',
    world_history_placeholder: 'Descreva os principais eventos históricos, civilizações antigas e conflitos recentes.',

    // Forms & Creation
    generate_with_ai: 'Gerar com IA',
    add_weapon: 'Adicionar Arma',
    edit_weapon: 'Editar Arma',
    add_new_weapon: 'Adicionar Nova Arma',
    damage: 'Dano',
    weapon_image: 'Imagem da Arma',
    save_weapon: 'Salvar Arma',
    confirm_delete_weapon: 'Tem certeza de que deseja excluir a arma "{name}"?',
    weapon_ai_placeholder: 'Uma espada forjada de uma estrela cadente',
    weapon_type_placeholder: 'Espada, Machado, Arco',
    weapon_damage_placeholder: '1d8 cortante',
    no_weapons_created: 'Nenhuma arma criada ainda.',
    start_creating_weapons: 'Clique em "Adicionar Arma" para começar a construir seu arsenal.',
    search_placeholder_weapons: 'Buscar armas...',
    all_types: 'Todos os tipos',
    generate_description_with_ai: 'Gerar Descrição com IA',
    weapon_description_ai_placeholder: 'ex: brilha quando orcs estão próximos',
    
    // Items
    'add_item': 'Adicionar Item',
    'edit_item': 'Editar Item',
    'add_new_item': 'Adicionar Novo Item',
    effects: 'Efeitos',
    item_icon: 'Ícone do Item',
    'save_item': 'Salvar Item',
    'item_ai_placeholder': 'Uma bússola que aponta para o que você deseja',
    'item_type_placeholder': 'Poção, Pergaminho, Anel',
    'effect_description_placeholder': 'Descreva o efeito mecânico',
    'add_effect': '+ Adicionar Efeito',
    'search_placeholder_items': 'Buscar itens...',
    'no_items_created': 'Nenhum item criado ainda.',
    'start_creating_items': 'Clique em "Adicionar Item" para criar tesouros para seu mundo.',
    'confirm_delete_item': 'Tem certeza de que deseja excluir o item "{name}"?',
    
    // Gear
    'add_gear': 'Adicionar Equipamento',
    'edit_gear': 'Editar Equipamento',
    'add_new_gear': 'Adicionar Novo Equipamento',
    slot: 'Encaixe',
    'armor_value': 'Valor de Armadura',
    'gear_image': 'Imagem do Equipamento',
    'save_gear': 'Salvar Equipamento',
    'gear_ai_placeholder': 'Armadura de couro encantada da floresta',
    'gear_type_placeholder': 'Armadura Leve, Roupa',
    'gear_slot_placeholder': 'Cabeça, Peito, Pés',
    'gear_armor_value_placeholder': '14 + Des, 5, ou Nenhum',
    'search_placeholder_gear': 'Buscar equipamento...',
    'all_slots': 'Todos os encaixes',
    'no_gear_created': 'Nenhuma roupa ou equipamento criado ainda.',
    'start_creating_gear': 'Clique em "Adicionar Equipamento" para criar armaduras e trajes para seu mundo.',
    'confirm_delete_gear': 'Tem certeza de que deseja excluir a peça de equipamento "{name}"?',
    'no_gear_match_search': 'Nenhum equipamento corresponde à sua busca.',
    
    // Spells
    'add_spell': 'Adicionar Feitiço',
    'edit_spell': 'Editar Feitiço',
    'add_new_spell': 'Adicionar Novo Feitiço',
    'school': 'Escola',
    'effect': 'Efeito',
    'mana_cost': 'Custo de Mana',
    'range': 'Alcance',
    'spell_icon': 'Ícone do Feitiço',
    'generate_spell_icon': 'Gerar Ícone de Feitiço',
    'save_spell': 'Salvar Feitiço',
    'spell_school': 'Escola de Magia',
    'spell_level': 'Nível do Feitiço',
    'cantrip': 'Truque',
    'spell_effect_prompt': 'Comando de Efeito do Feitiço',
    'spell_ai_placeholder': 'Uma bola de fogo que ricocheteia entre inimigos',
    'spell_school_placeholder': 'Evocação, Ilusão',
    'spell_effect_placeholder': 'Descreva o que o feitiço faz...',
    'search_placeholder_spells': 'Buscar feitiços...',
    'all_schools': 'Todas as escolas',
    'all_levels': 'Todos os níveis',
    'no_spells_created': 'Nenhum feitiço criado ainda.',
    'start_creating_spells': 'Clique em "Adicionar Feitiço" para criar a magia do seu mundo.',
    'confirm_delete_spell': 'Tem certeza de que deseja excluir o feitiço "{name}"?',
    generate_effect_with_ai: 'Gerar Efeito com IA',
    spell_effect_ai_placeholder: 'ex: cria uma ilusão de um dragão',
    
    // Classes
    'add_class': 'Adicionar Classe',
    'edit_class': 'Editar Classe',
    'add_new_class': 'Adicionar Nova Classe',
    'class_name': 'Nome da Classe',
    'no_spells_for_class': 'Nenhum feitiço criado ainda. Vá para a tela de Feitiços para adicionar alguns.',
    'search_placeholder_spells_class': 'Buscar feitiços...',
    'save_class': 'Salvar Classe',
    'no_classes_created': 'Nenhuma classe criada ainda.',
    'start_creating_classes': 'Clique em "Adicionar Classe" para definir os arquétipos do seu mundo.',
    'confirm_delete_class': 'Tem certeza de que deseja excluir a classe "{name}"?',
    'class_ai_placeholder': 'Um guerreiro que comanda as sombras',
    'ability_placeholder': 'Habilidade #{index}',
    'add_ability': '+ Adicionar Habilidade',
    'trait_placeholder': 'Traço #{index}',
    'add_trait': '+ Adicionar Traço',
    
    // Races
    'add_race': 'Adicionar Raça',
    'edit_race': 'Editar Raça',
    'add_new_race': 'Adicionar Nova Raça',
    'race_name': 'Nome da Raça',
    'traits_and_abilities': 'Traços e Habilidades',
    'save_race': 'Salvar Raça',
    'no_races_created': 'Nenhuma raça criada ainda.',
    'start_creating_races': 'Clique em "Adicionar Raça" para definir os povos do seu mundo.',
    'confirm_delete_race': 'Tem certeza de que deseja excluir a raça "{name}"?',
    'race_ai_placeholder': 'Uma raça de humanoides cristalinos',

    // Characters
    'create_character': 'Criar Personagem',
    'edit_character': 'Editar Personagem',
    'create_new_character': 'Criar Novo Personagem',
    'physical_appearance': 'Aparência Física',
    'background_history': 'Histórico / Background',
    'attributes': 'Atributos',
    'health_points': 'Pontos de Vida',
    'mana_points': 'Pontos de Mana',
    'spell_slots': 'Espaços de Magia',
    'level_n_slots': 'Espaços Nvl {level}',
    'no_spell_slots': 'A classe deste personagem não possui magias.',
    'new_attribute_name': 'Novo nome de atributo',
    'save_changes': 'Salvar Alterações',
    'no_characters_created': 'Nenhum personagem criado ainda.',
    'start_creating_characters': 'Clique em "Criar Personagem" para dar vida aos seus heróis.',
    'confirm_delete_character': 'Tem certeza de que deseja excluir o personagem "{name}"?',
    inventory: 'Inventário',
    inventory_management: 'Gerenciamento de Inventário',
    no_items_for_character: 'Nenhum item criado no sistema.',
    no_gear_for_character: 'Nenhum equipamento criado no sistema.',
    no_weapons_for_character: 'Nenhuma arma criada no sistema.',
    'search_placeholder_items_character': 'Buscar itens para adicionar...',
    'search_placeholder_gear_character': 'Buscar equipamentos para adicionar...',
    'search_placeholder_weapons_character': 'Buscar armas para adicionar...',
    'character_portrait': 'Retrato do Personagem',
    'ai_generation_reference': 'Referência para Geração de IA',
    'upload_photo_for_ai': 'Carregue uma foto para a IA usar como inspiração.',
    'upload_reference_photo': 'Carregar Foto de Referência',
    'generate_from_photo': 'Gerar a partir da Foto',
    'change_photo': 'Alterar Foto',
    'remove_photo': 'Remover Foto',
    'upload_portrait': 'Carregar Retrato',
    'character_inventory': 'Inventário do Personagem',
    quantity: 'Qtd',
    increase_quantity: 'Aumentar quantidade',
    decrease_quantity: 'Diminuir quantidade',
    equip: 'Equipar',
    unequip: 'Desequipar',
    equip_main: 'Equipar Principal',
    equip_off: 'Equipar Secundária',
    backpack: 'Mochila',
    'search_in_backpack': 'Buscar na mochila...',
    equipped_gear: 'Equipamento Vestido',
    equipped_weapons: 'Armas Equipadas',
    head: 'Cabeça',
    chest: 'Peito',
    legs: 'Pernas',
    hands: 'Mãos',
    feet: 'Pés',
    accessory: 'Acessório',
    main_hand: 'Mão Principal',
    off_hand: 'Mão Secundária',
    add_to_backpack: 'Adicionar à Mochila',
    calculated_combat_stats: 'Atributos de Combate',
    damage_output: 'Dano Causado',
    drop_to_equip: 'Arraste para Equipar',
    drop_to_unequip: 'Solte na Mochila',

    // Campaign Gen
    'ai_dungeon_master': 'Mestre de Jogo IA',
    campaign_started_prompt: 'Interaja com o mundo. Descreva suas ações, fale com personagens e veja como a história se desenrola.',
    campaign_not_started_prompt: 'Descreva um tema ou ponto de partida, e a IA iniciará uma campanha dinâmica para você.',
    'theme_selection_title': 'Escolha um Tema de Campanha',
    'theme_high_fantasy': 'Alta Fantasia',
    'theme_high_fantasy_desc': 'Missões épicas, heróis e vilões claros, e o destino do mundo em jogo.',
    'theme_grimdark': 'Grimdark',
    'theme_grimdark_desc': 'Um mundo sombrio e moralmente cinzento, onde cada vitória tem um custo.',
    'theme_mystery': 'Mistério',
    'theme_mystery_desc': 'Desvende um crime complexo ou uma conspiração usando sua inteligência.',
    'theme_intrigue': 'Intriga Política',
    'theme_intrigue_desc': 'Navegue por uma teia de segredos, alianças e traições nos salões do poder.',
    'theme_exploration': 'Exploração',
    'theme_exploration_desc': 'Viaje para o desconhecido, descubra terras perdidas e mapeie a selva.',
    'theme_custom': 'Personalizado',
    'theme_custom_desc': 'Escreva sua própria ideia de campanha única do zero.',
    'campaign_details_placeholder': 'Adicione detalhes específicos ou reviravoltas...',
    'campaign_custom_placeholder': 'Descreva sua ideia de campanha...',
    start_campaign: 'Iniciar Campanha',
    chat_input_placeholder: 'O que você faz?',
    error_starting_campaign: 'Falha ao iniciar a campanha. Verifique o console para detalhes.',
    error_sending_message: 'Falha ao obter resposta da IA. Por favor, tente novamente.',

    // Image Gen
    ai_image_generator: 'Gerador de Imagens IA',
    image_generator_subtitle: 'Dê vida ao seu mundo. Gere arte para suas criações.',
    generation_type: 'Tipo de Geração',
    landscape: 'Paisagem',
    world_map: 'Mapa do Mundo',
    other: 'Outro',
    prompt: 'Comando',
    additional_details: 'Detalhes Adicionais',
    image_gen_placeholder_other: 'Um dragão feroz guardando seu tesouro',
    image_gen_placeholder_details: 'Iluminação cinematográfica, durante uma tempestade',
    image_gen_output_placeholder: 'Sua imagem gerada aparecerá aqui.',
    final_prompt: 'Comando Final',
    error_generating_image: 'Falha ao gerar imagem. Verifique o console para detalhes.',
    error_unexpected: 'Ocorreu um erro inesperado.',

    // NPCs
    edit_npc: 'Editar NPC',
    add_new_npc: 'Adicionar Novo NPC',
    npc_ai_placeholder: 'Um mestre do saber élfico recluso',
    race: 'Raça',
    role: 'Papel',
    npc_race_placeholder: 'Humano, Elfo, Orc',
    npc_role_placeholder: 'Fornecedor de Missão, Mercador',
    portrait_style: 'Estilo do Retrato',
    save_npc: 'Salvar NPC',
    confirm_delete_npc: 'Tem certeza que quer excluir o NPC "{name}"?',
    search_placeholder_npcs: 'Buscar NPCs...',
    all_races: 'Todas as raças',
    all_roles: 'Todos os papéis',
    no_npcs_created: 'Nenhum NPC criado ainda.',
    start_creating_npcs: 'Clique em "Adicionar Novo NPC" para popular seu mundo com personagens.',

    // Creatures
    edit_creature: 'Editar Criatura',
    add_new_creature: 'Adicionar Nova Criatura',
    creature_ai_placeholder: 'Uma aranha gigante que tece teias de vidro',
    challenge_rating: 'Nível de Desafio',
    creature_type_placeholder: 'Besta, Monstruosidade, Morto-vivo',
    creature_cr_placeholder: '1/2, 5 (1.800 XP)',
    creature_hp_placeholder: 'ex: 45 (6d10 + 12)',
    creature_ac_placeholder: 'ex: 15 (Armadura Natural)',
    creature_ab_placeholder: 'ex: +5',
    save_creature: 'Salvar Criatura',
    confirm_delete_creature: 'Tem certeza que quer excluir la criatura "{name}"?',
    search_placeholder_creatures: 'Buscar criaturas...',
    no_creatures_created: 'Nenhuma criatura criada ainda.',
    start_creating_creatures: 'Clique em "Adicionar Nova Criatura" para criar os monstros do seu mundo.',
    ability: 'Habilidade',
    add_ability_creature: '+ Adicionar Habilidade',
    ability_placeholder_creature: 'Habilidade nº{index}',

    // Effect Types
    'effect_type_healing': 'Cura',
    'effect_type_damage': 'Dano',
    'effect_type_buff': 'Buff',
    'effect_type_debuff': 'Debuff',
    'effect_type_utility': 'Utilidade',
    'effect_type_other': 'Outro',

    // Spell Schools
    'spell_school_evocation': 'Evocação',
    'spell_school_illusion': 'Ilusão',
    'spell_school_necromancy': 'Necromancia',
    'spell_school_conjuration': 'Conjuração',
    'spell_school_abjuration': 'Abjuração',
    'spell_school_divination': 'Adivinhação',
    'spell_school_enchantment': 'Encantamento',
    'spell_school_transmutation': 'Transmutação',
    'spell_school_artificing': 'Artificeria',
    'spell_school_psionics': 'Psiônica',
    
    // Attributes
    'Strength': 'Força',
    'Dexterity': 'Destreza',
    'Constitution': 'Constituição',

    // Project Management
    'new_project': 'Novo',
    'load_project': 'Carregar',
    'save_project': 'Salvar',
    'confirm_new_project': 'Tem certeza que quer começar um novo projeto? Todos os dados atuais serão perdidos.',
    'project_loaded_successfully': 'Projeto carregado com sucesso!',
    'error_loading_project': 'Falha ao carregar o arquivo do projeto. O arquivo pode estar corrompido ou no formato errado.',
    
    // Deletion
    'delete_weapon': '- Excluir Arma',
    'delete_item': '- Excluir Item',
    'delete_gear': '- Excluir Equipamento',
    'delete_spell': '- Excluir Feitiço',
    'delete_npc': '- Excluir NPC',
    'delete_creature': '- Excluir Criatura',
    'delete_class': '- Excluir Classe',
    'delete_race': '- Excluir Raça',
    'delete_character': '- Excluir Personagem',
    'cancel_deletion': 'Cancelar Exclusão',
    'confirm_deletion': 'Confirmar Exclusão',
    warning_delete_dependency: "Aviso: Os seguintes personagens usam este {entity}: {character_list}. Excluí-lo também o removerá de suas fichas. Tem certeza de que deseja excluir {name}?",
    block_delete_dependency: "Não é possível excluir {name}. Os seguintes personagens têm este {entity} atribuído: {character_list}. Por favor, atualize esses personagens primeiro.",
    entity_weapon: "arma",
    entity_item: "item",
    entity_gear: "peça de equipamento",
    entity_spell: "feitiço",
    entity_class: "classe",
    entity_race: "raça",
    
    // Analytics Screen
    analytics_title: 'Análises do Mundo',
    analytics_subtitle: 'Visualize a composição do seu mundo de RPG com estes gráficos e estatísticas.',
    items_by_type: 'Itens por Tipo',
    spells_by_school: 'Feitiços por Escola',
    creatures_by_cr: 'Criaturas por Nível de Desafio',
    npcs_by_role: 'NPCs por Papel',
    weapons_by_type: 'Armas por Tipo',
    no_data_for_chart: 'Nenhum dado disponível para exibir.',
    challenge_rating_group: 'ND {range}',
  },
};

export const languageMap: { [key: string]: string } = {
  en: 'English',
  es: 'Español',
  'pt-BR': 'Português (Brasil)',
};

const languageFullNames: { [key: string]: string } = {
    en: 'English',
    es: 'Spanish',
    'pt-BR': 'Brazilian Portuguese',
};

interface LanguageContextType {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string, replacements?: { [key: string]: string | number }) => string;
  languageFullName: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window === 'undefined') {
        return 'en';
    }
    const savedLang = localStorage.getItem('language');
    return savedLang && translations[savedLang] ? savedLang : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string, replacements?: { [key: string]: string | number }) => {
    let translation = translations[language]?.[key] || translations['en']?.[key] || key;
    if (replacements) {
        Object.keys(replacements).forEach(rKey => {
            const value = replacements[rKey];
            translation = translation.replace(`{${rKey}}`, String(value));
        });
    }
    return translation;
  };
  
  const languageFullName = languageFullNames[language] || 'English';

  const value = { language, setLanguage, t, languageFullName };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};